### ISSUE TITLE
Name of repo not descriptive enough

### ISSUE THREAD

**Issue by OscarGodson** [Getable/input-field#1]
![](http://i.kinja-img.com/gawker-media/image/upload/s--iZmEvNY5--/17ielvjicc32pjpg.jpg)

**Comment by ben-ng** [comment]
sir, i am having trouble reproducing that face. can you send instructions?

**Comment by cstumph** [comment]
Wontfix. OP is a douche.

**Comment by techwraith** [comment]
Wait, is the name of the repo _not_ descriptive enough, or is the issue that the name of the repo _is_ descriptive enough? It's not 100% clear from your bug report.

**Comment by joeybaker** [comment]
I'm not sure what your bug is? Can you please provide reproduction steps?
